image: oarteam/batsim_ci

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - update_dependencies_cache
  - test
  - coverage
  - deploy

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    - ./ci/build.bash
  artifacts:
    paths:
      - /builds/batsim/batsched/build

###############################################################################
# Dependencies cache stage
###############################################################################
update_dependencies_cache:
  stage: update_dependencies_cache
  script:
    - ./ci/update-dependencies-cache.bash

###############################################################################
# Test stage
###############################################################################
test_pinned_batsim:
  stage: test
  script:
    - nix-shell ./ci -A test_pinned --command 'bash ./ci/run-tests.bash'
  dependencies:
    - build
  artifacts:
    paths:
      - /builds/batsim/batsched/build

test_dev_batsim:
  stage: test
  script:
    - nix-shell ./ci -A test_dev --command 'bash ./ci/run-tests.bash'
  dependencies:
    - build

###############################################################################
# Coverage stage
###############################################################################
coverage:
  stage: coverage
  script:
    - nix-shell ./ci -A test_deps_pinned --command 'bash ./ci/analyze-coverage.bash'
  dependencies:
    - test_pinned_batsim
  artifacts:
    paths:
      - /builds/batsim/batsched/cover

###############################################################################
# Deploy stage
###############################################################################
deploy_coverage:
  stage: deploy
  script:
      # Pushes Batsim's code doc (doxygen) onto the gforge website.
      # SSH setup (do NOT run these commands on your machine)
      - eval $(ssh-agent -s)
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
      # Finally push the code documentation on the gforge website
      - rsync -rlgoDz --delete cover/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs/batsched/coverage
  dependencies:
    - coverage
  only:
    - master

deploy_batsim_dev_cachix:
  stage: deploy
  script:
    - ./ci/update-batsim_dev-cache.bash
  only:
    - master
